
version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pg-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"  # Changed to use port 5433
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - pg-network

  ingest:
    image: taxi_ingest:v001
    container_name: ingest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pg-network
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=pg-database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ny_taxi
      - TABLE_NAME=yellow_taxi_trips
      - DATA_URL=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz
    entrypoint: ["python", "ingest_data.py"]
    command: [
      "--user", "postgres",
      "--password", "postgres",
      "--host", "pg-database",
      "--port", "5432",
      "--db", "ny_taxi",
      "--table-name", "yellow_taxi_trips",
      "--url", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
    ]

networks:
  pg-network:
    driver: bridge


